tools: add deployment commands

diff --git a/tools/package b/tools/package
--- a/tools/package
+++ b/tools/package
@@ -3,7 +3,8 @@
 set -e
 
 ROOT=${ROOT:-$(pwd)}
-SERVICE=$1
+TYPE=$1
+SERVICE=$2
 
 service_dir=$ROOT/$SERVICE
 build_dir=$service_dir/build
@@ -13,7 +14,7 @@ display_usage () {
 }
 
 # Check if there are at least 2 arguments
-if [ $# -lt 1 ]; then
+if [ $# -lt 2 ]; then
     display_usage
     exit 1
 fi
@@ -41,17 +42,28 @@ cleanup () {
 }
 trap cleanup EXIT
 
-clean () {
-    if [ -z $build_dir ]; then
-        echo "\$build_dir not set. Aborting"
-        exit 1
-    fi
-    if [ -d $build_dir ]; then
-        echo "Removing $build_dir"
-        rm -r $build_dir
-    else
-        echo "$build_dir does not exit. Skipping"
+package_cloudformation () {
+    if [ -f $service_dir/build/template.yaml ]; then
+        pushd $build_dir
+        aws cloudformation package \
+            --s3-bucket ${S3_BUCKET:-${USER}-src} \
+            --s3-prefix "artifacts" \
+            --template-file template.yaml \
+            --output-template-file template.out || {
+                # Delay failure so we can popd
+                FAILED=yes
+            }
+        popd
+        if [ ! -z $FAILED ]; then
+            exit 1
+        fi
     fi
 }
 
-clean
+type package_$TYPE | grep -q "function" &>/dev/null || {
+    echo "Unsupported type: $TYPE"
+    echo
+    display_usage
+    exit 1
+}
+package_$TYPE
diff --git a/tools/tests-integ b/tools/tests-integ
--- a/tools/tests-integ
+++ b/tools/tests-integ
@@ -7,8 +7,7 @@ TYPE=$1
 SERVICE=$2
 
 service_dir=$ROOT/$SERVICE
-tests_dir=$service_dir/tests/unit
-build_dir=$service_dir/build
+tests_dir=$service_dir/tests/integ
 
 display_usage () {
     echo "Usage: $0 TYPE SERVICE"
@@ -43,40 +42,34 @@ cleanup () {
 }
 trap cleanup EXIT
 
-# Unit tests for python3
-tests_python3 () {
-    # Check if this service skip tests
+# Unit tests for cloudformation
+tests_cloudformation () {
+    # Checks if this service skips tests
     yq -r ' .flags["skip-tests"] | if . == null then false else . end ' $service_dir/metadata.yaml | grep -q true && {
-        echo "Skipping unit tests for $SERVICE"
+        echo "Skipping integration tests for $SERVICE"
         exit 0
     }
 
-    # If there are no unit tests folder, we skip the unit tests
-    if [ ! -d $tests_dir ]; then
-        echo "Missing unit tests folder in $SERVICE. Skipping"
-        exit 1
-    fi
+    # Skip tests on environment where we shouldn't run tests
+    yq -r ' .'${ENVIRONMENT}'.flags["can-test"] | if . == null then true else . end ' $ROOT/environments.yaml | grep -q true || {
+        echo "The environment $ENVIRONMENT does not support tests. Skipping"
+        exit 0
+    }
 
-    # We need a build folder to perform tests
-    if [ ! -d $build_dir ]; then
-        echo "Missing build folder in $SERVICE"
+    # If there are no integration tests folder, we skip the unit tests
+    if [ ! -d $tests_dir ]; then
+        echo "Missing integration tests folder in $SERVICE. Skipping"
         exit 1
     fi
 
     if [ -z $PYTHONPATH ]; then
-        PYTHONPATH=$ROOT/shared/tests/unit
+        PYTHONPATH=$ROOT/shared/tests/integ
     else
-        PYTHONPATH=$PYTHONPATH:$ROOT/shared/tests/unit
+        PYTHONPATH=$PYTHONPATH:$ROOT/shared/tests/integ
     fi
 
-    ECOM_BUILD_DIR=$build_dir \
-    PYTHONPATH=$PYTHONPATH \
-    AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID \
-    AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY \
-    AWS_DEFAULT_REGION=eu-west-1 \
-    pytest $tests_dir \
-        --cov $build_dir \
-        --cov-config $ROOT/shared/tests/unit/coveragerc
+    ECOM_ENVIRONMENT=${ENVIRONMENT} \
+    pytest $tests_dir
 }
 
 type tests_$TYPE | grep -q "function" &>/dev/null || {
